<?php
return[
    'EMAIL_SMTP'=>'smtp.exmail.qq.com',
    'EMAIL_ADDRESS'=>'1140514109@qq.com',
    'EMAIL_LOGINNAME'=>'wangxi@refineit.com.cn',
    'EMAIL_PASSWORD'=>'Q13CDYAvgnW2Bvlo',
    'port'=>465
];
?>